
export const GET_DATA_REQUEST="GET_DATA_REQUEST";

export const GET_DATA_SUCCESS="GET_DATA_SUCCESS";

export const GET_DATA_FAILURE="GET_DATA_FAILURE";

export const MYSTORY_REQUEST="MYSTORY_REQUEST";

export const MYSTORY_SUCCESS="MYSTORY_SUCCESS";

export const MYSTORY_FAILURE="MYSTORY_FAILURE";

export const MYSTORY_DELETE_REQUEST="MYSTORY_DELETE_REQUEST"

export const MYSTORY_DELETE_SUCCESS="MYSTORY_DELETE_SUCCESS"

export const MYSTORY_DELETE_FAILURE="MYSTORY_DELETE_FAILURE"

export const MYSTORY_EDIT_REQUEST="MYSTORY_EDIT_REQUEST"

export const MYSTORY_EDIT_SUCCESS="MYSTORY_EDIT_SUCCESS"

export const MYSTORY_EDIT_FAILURE="MYSTORY_EDIT_FAILURE"